stages:
  - build
  - test
  - post-test
  - release

variables:
  GIT_DEPTH: "3"
  SAST_TARGET: schemathesis
  SONARQUBE_TARGET: schemathesis,test
  PYLINT_TARGET: schemathesis test
  PYTEST_COVERAGE_TARGET: schemathesis

include:
  - 'https://ci-files.skypicker.com/templates/build/black.yml'
  - 'https://ci-files.skypicker.com/templates/build/tox_init.yml'
  - 'https://ci-files.skypicker.com/templates/test/.tox.yaml'
  - 'https://ci-files.skypicker.com/templates/test/dependency_scanning.yml'

.tox_tests:
  extends: .tox
  artifacts:
    paths:
      - reports/
      - .coverage*

mypy:
  extends: .tox
  variables:
    TOX_ENVIRONMENT: mypy

pylint:
  extends: .tox
  variables:
    TOX_ENVIRONMENT: pylint

py36-tests:
  extends: .tox_tests
  variables:
    TOX_ENVIRONMENT: py36

py37-tests:
  extends: .tox_tests
  variables:
    TOX_ENVIRONMENT: py37

py38-tests:
  extends: .tox_tests
  variables:
    TOX_ENVIRONMENT: py38

tox_tests_coverage:
  extends: .tox_tests
  stage: post-test
  dependencies:
    - tox_init
    - py36-tests
    - py37-tests
    - py38-tests
  needs:
    - tox_init
    - py36-tests
    - py37-tests
    - py38-tests
  before_script:
    - mkdir -p $CI_PROJECT_DIR/coverage-reports
  artifacts:
    paths:
      - coverage-reports/
  script:
    - tox -e coverage-report -- -o $CI_PROJECT_DIR/coverage-reports/coverage-integration.xml
