- name: Fix it now
  pattern: "[fF][iI][xX][mM][eE]"
  filename:
    - "*.py"

- name: No sys.path changes
  pattern: "sys\\.path\\.append|sys\\.path\\.insert"
  filename:
    - "src/**.py"

- name: IPython debug leftover
  pattern: "IPython\\.embed()"
  filename:
    - "*.py"

- name: Leftover print
  pattern: "print\\("
  filename:
    - ^(?!.*conftest).*\.py$

- name: Use relative imports
  pattern: "import schemathesis|from schemathesis"
  filename:
    - "src/**.py"
