import pytest

from schemathesis.specs.openapi.stateful.dependencies import naming


@pytest.mark.parametrize(
    ["word", "expected"],
    [
        ("sheep", "sheep"),
        ("aircraft", "aircraft"),
        ("information", "information"),
        ("software", "software"),
        ("oxen", "ox"),
        ("feet", "foot"),
        ("geese", "goose"),
        ("teeth", "tooth"),
        ("dice", "die"),
        ("axes", "axe"),
        ("parties", "party"),
        ("cities", "city"),
        ("flies", "fly"),
        ("berries", "berry"),
        ("glasses", "glass"),
        ("classes", "class"),
        ("passes", "pass"),
        ("masses", "mass"),
        ("boxes", "box"),
        ("foxes", "fox"),
        ("axes", "axe"),
        ("buzzes", "buzz"),
        ("fizzes", "fizz"),
        ("churches", "church"),
        ("watches", "watch"),
        ("beaches", "beach"),
        ("wishes", "wish"),
        ("bushes", "bush"),
        ("crashes", "crash"),
        ("uses", "use"),
        ("houses", "house"),
        ("reuses", "reuse"),
        ("cases", "case"),
        ("vases", "vase"),
        ("gases", "gas"),
        ("statuses", "status"),
        ("buses", "bus"),
        ("viruses", "virus"),
        ("cars", "car"),
        ("dogs", "dog"),
        ("cats", "cat"),
        ("days", "day"),
        ("keys", "key"),
        ("car", "car"),
        ("book", "book"),
        ("party", "party"),
    ],
)
def test_to_singular(word, expected):
    assert naming.to_singular(word) == expected


@pytest.mark.parametrize(
    ["word", "expected"],
    [
        ("sheep", "sheep"),
        ("information", "information"),
        ("equipment", "equipment"),
        ("ox", "oxen"),
        ("foot", "feet"),
        ("goose", "geese"),
        ("tooth", "teeth"),
        ("die", "dice"),
        ("echo", "echoes"),
        ("volcano", "volcanoes"),
        ("party", "parties"),
        ("city", "cities"),
        ("fly", "flies"),
        ("berry", "berries"),
        ("day", "days"),
        ("key", "keys"),
        ("boy", "boys"),
        ("ray", "rays"),
        ("class", "classes"),
        ("glass", "glasses"),
        ("pass", "passes"),
        ("mass", "masses"),
        ("bus", "buses"),
        ("gas", "gases"),
        ("focus", "focuses"),
        ("status", "statuses"),
        ("box", "boxes"),
        ("fox", "foxes"),
        ("tax", "taxes"),
        ("buzz", "buzzes"),
        ("fizz", "fizzes"),
        ("quiz", "quizzes"),
        ("church", "churches"),
        ("watch", "watches"),
        ("beach", "beaches"),
        ("wish", "wishes"),
        ("bush", "bushes"),
        ("crash", "crashes"),
        ("car", "cars"),
        ("dog", "dogs"),
        ("book", "books"),
        ("house", "houses"),
        ("table", "tables"),
        ("use", "uses"),
    ],
)
def test_to_plural(word, expected):
    assert naming.to_plural(word) == expected


@pytest.mark.parametrize(
    ["name", "prefixes", "suffixes", "expected"],
    [
        pytest.param("UserResponse", ["get"], ["response"], "User", id="suffix-only"),
        pytest.param("GetUser", ["get"], ["response"], "User", id="prefix-only"),
        pytest.param("GetUserResponse", ["get"], ["response"], "User", id="prefix-then-suffix-bug"),
        pytest.param("GETUserRESPONSE", ["get"], ["response"], "User", id="preserves-case"),
        pytest.param("User", ["get"], ["response"], "User", id="no-match"),
        pytest.param("CreateUser", ["get"], ["response"], "CreateUser", id="different-prefix"),
        pytest.param("", ["get"], ["response"], "", id="empty-string"),
        pytest.param("get", ["get"], [], "", id="becomes-empty"),
        pytest.param("GetUserResponse", [], [], "GetUserResponse", id="no-affixes"),
        pytest.param("GetUser", ["list", "get", "create"], ["response"], "User", id="first-prefix-wins"),
        pytest.param("UserResponse", ["get"], ["data", "response"], "User", id="first-suffix-wins"),
        pytest.param("  GetUser  ", ["get"], [], "User", id="strips-whitespace"),
        pytest.param("GetGetResponse", ["get"], ["response"], "Get", id="suffix-on-original"),
    ],
)
def test_strip_affixes(name, prefixes, suffixes, expected):
    assert naming.strip_affixes(name, prefixes, suffixes) == expected
