name: Benchmarks

on:
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SCHEMATHESIS_BENCHMARK_SEED: "42"
  PYTHONHASHSEED: "0"

jobs:
  benchmarks:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      matrix:
        shard: [1, 2, 3, 4]
    name: "Run benchmarks (Shard #${{ matrix.shard }})"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

      - name: Install
        run: |
          uv venv
          uv pip install ".[bench]"

      - name: Run benchmarks
        uses: CodSpeedHQ/action@f99becdce5e5d51fd556489ebef684f4ecfd6286 # v4.18.5
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          mode: "simulation"
          run: .venv/bin/pytest benches/* --codspeed -p no:schemathesis -p no:hypothesispytest -p no:subtests -p no:anyio --test-group=${{ matrix.shard }} --test-group-count=4
