name: Checks for every commit

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  commitsar:
    name: Verify commit messages
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Run commitsar
        uses: aevea/commitsar@909c3ab676c9af63cb84f2e38f395c7e89829b04 # v1.0.3
