name: Run corpus tests

on:
  schedule:
    # Every day at 00:00
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:

  corpus-default:
    name: Default corpus tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: true

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - uses: astral-sh/setup-uv@v7
        with:
          cache-dependency-glob: "**/pyproject.toml"

      - run: uvx --from=".[tests]" pytest test-corpus/test_corpus.py -n auto -k test_default --durations=20 --dist=worksteal

  corpus-coverage:
    name: Corpus tests for the coverage phase (${{ matrix.mode }})
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        mode: [positive, negative]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: true

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - uses: astral-sh/setup-uv@v7
        with:
          cache-dependency-glob: "**/pyproject.toml"

      - run: uvx --from=".[tests]" pytest test-corpus/test_corpus.py -n auto -k "test_coverage_phase and ${{ matrix.mode }}" --durations=20 --dist=worksteal

  corpus-inference:
    name: Corpus tests for dependency inference
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: true

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - uses: astral-sh/setup-uv@v7
        with:
          cache-dependency-glob: "**/pyproject.toml"

      - run: uvx --from=".[tests]" pytest test-corpus/test_inference.py -n auto --durations=20 --dist=worksteal

  corpus-stateful:
    name: Corpus tests for stateful testing
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: true

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - uses: astral-sh/setup-uv@v7
        with:
          cache-dependency-glob: "**/pyproject.toml"

      - run: uvx --from=".[tests]" pytest test-corpus/test_corpus.py -n auto -k test_stateful --durations=20 --dist=worksteal

  corpus-graphql:
    name: GraphQL corpus tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: true

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - uses: astral-sh/setup-uv@v7
        with:
          cache-dependency-glob: "**/pyproject.toml"

      - run: uvx --from=".[tests]" pytest test-corpus/test_corpus.py -k test_graphql -n auto --durations=20 --dist=worksteal
