name: Update pre-commit

on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

jobs:
  release:
    name: Update pre-commit
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1
          submodules: true

      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

      - run: uvx prek autoupdate

      - name: Open pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          title: Update pre-commit
          body: Automatically update pre-commit
          commit-message: 'chore: Update pre-commit'
          committer: 'CI on behalf of the Schemathesis team <team@schemathesis.io>'
          author: 'CI on behalf of the Schemathesis team <team@schemathesis.io>'
          branch: "create-pull-request/update-pre-commit"
